# Generated by Django 5.1.15 on 2026-06-03 20:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Kurzkennung des Strings.', max_length=80, unique=True)),
                ('name', models.CharField(help_text='Anzeigename des Strings.', max_length=160)),
                ('purpose', models.TextField(help_text='Wofür dieser String gedacht ist.')),
                ('sequence', models.JSONField(default=list, help_text='Geordnete Liste von Schritten: [{"slug": ..., "note": ...}, ...].')),
                ('total_duration', models.PositiveIntegerField(help_text='Geschätzte Gesamtdauer in Minuten.')),
                ('context_notes', models.TextField(blank=True, default='', help_text='Hinweise zum Einsatz.')),
                ('scrum_context', models.CharField(blank=True, default='', help_text='Optionaler Scrum-Kontext (z. B. retrospektive, planning).', max_length=30)),
            ],
            options={
                'verbose_name': 'String-Template',
                'verbose_name_plural': 'String-Templates',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_id', models.PositiveIntegerField(help_text='Stabile Nummer der Methode aus dem Seed-Datensatz.', unique=True)),
                ('name', models.CharField(help_text='Anzeigename, zum Beispiel 1-2-4-All.', max_length=120)),
                ('slug', models.SlugField(help_text='Kurzkennung für Verknüpfungen, zum Beispiel 1-2-4-all.', max_length=80, unique=True)),
                ('type', models.CharField(choices=[('official', 'official'), ('variation', 'variation'), ('punctuation', 'punctuation'), ('in_development', 'in_development')], default='official', help_text='official | variation | punctuation | in_development.', max_length=20)),
                ('base_structure', models.CharField(blank=True, default='', help_text='Bei Varianten: Slug der Original-Struktur. Sonst leer.', max_length=80)),
                ('edition', models.CharField(choices=[('original', 'original'), ('extended', 'extended')], default='original', help_text='original = die 33 Kern-LS; extended = später ergänzte.', max_length=20)),
                ('short_desc', models.TextField(help_text='Verständliche Kurzbeschreibung (1–3 Sätze).')),
                ('source_url', models.URLField(help_text='Link zur Original-Detailseite (Quelle).', max_length=300)),
                ('purpose_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, help_text='Zweck-Kategorien (eine oder mehrere) aus den erlaubten Werten.', size=None)),
                ('arc_role', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, help_text='Bogen-Rolle(n): öffnen/divergieren/konvergieren/schließen.', size=None)),
                ('group_size_min', models.PositiveIntegerField(help_text='Empfohlene Mindest-Teilnehmerzahl.')),
                ('group_size_max', models.PositiveIntegerField(blank=True, help_text='Empfohlene Höchstzahl; leer = nach oben offen.', null=True)),
                ('duration_min', models.PositiveIntegerField(help_text='Mindestdauer in Minuten.')),
                ('duration_max', models.PositiveIntegerField(help_text='Übliche Höchstdauer in Minuten.')),
                ('online_capable', models.BooleanField(help_text='True, wenn online (Remote) gut durchführbar.')),
                ('materials', models.TextField(blank=True, default='', help_text='Materialien und Raumhinweise.')),
                ('difficulty', models.CharField(choices=[('leicht', 'leicht'), ('mittel', 'mittel'), ('fortgeschritten', 'fortgeschritten')], help_text='leicht | mittel | fortgeschritten.', max_length=20)),
                ('typical_predecessors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, help_text='Slugs von Strukturen, die typischerweise davor stehen.', size=None)),
                ('typical_successors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, help_text='Slugs von Strukturen, die typischerweise danach stehen.', size=None)),
                ('scrum_use', models.TextField(blank=True, default='', help_text='Einsatz im Scrum-Kontext (Retro, Planning, …).')),
                ('design_elements', models.JSONField(default=dict, help_text='Die 5 Designelemente: einladung, raum_materialien, einbindung, gruppenkonfiguration, ablauf_dauer.')),
                ('description_origin', models.CharField(choices=[('uebernommen', 'uebernommen'), ('eigen', 'eigen')], default='uebernommen', help_text='uebernommen (mit Attribution) oder eigen.', max_length=20)),
                ('attribution', models.TextField(blank=True, default='', help_text='Namensnennung + Lizenz bei übernommenen Inhalten.')),
            ],
            options={
                'verbose_name': 'Struktur',
                'verbose_name_plural': 'Strukturen',
                'ordering': ['structure_id'],
            },
        ),
    ]
