# Generated by Django 5.1.15 on 2026-06-04 10:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='embodied_principles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=4), blank=True, default=list, help_text='IDs der besonders verkörperten LS-Prinzipien (P1–P10), siehe data/ls_principles.json.', size=None),
        ),
        migrations.AddField(
            model_name='structure',
            name='guide',
            field=models.JSONField(blank=True, default=dict, help_text='Ausführlicher Detailguide (Ebene 2, spiegelt die Quellseite): was_wird_moeglich, einladung, beispielsaetze[], schritte[], varianten[], tipps[], anlaesse[], material_setup.'),
        ),
        migrations.AddField(
            model_name='structure',
            name='objective',
            field=models.CharField(blank=True, default='', help_text='Kanonisches Ziel (LS Selection Matchmaker): das eine Ziel, das die Struktur erfüllt – Matching-Schlüssel. Quelle: data/ls_objectives.json.', max_length=300),
        ),
    ]
