# Generated by Django 5.1.15 on 2026-06-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bilingual_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='attribution',
            field=models.JSONField(blank=True, default=dict, help_text='Namensnennung + Lizenz, zweisprachig {"de": …, "en": …}.'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='design_elements',
            field=models.JSONField(default=dict, help_text='Die 5 Designelemente, je zweisprachig {"de": …, "en": …}: einladung, raum_materialien, einbindung, gruppenkonfiguration, ablauf_dauer.'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='guide',
            field=models.JSONField(blank=True, default=dict, help_text='Ausführlicher Detailguide (Ebene 2, spiegelt die Quellseite), je Feld zweisprachig {"de": …, "en": …}: was_wird_moeglich, einladung, beispielsaetze[], schritte[], varianten[], tipps[], anlaesse[], material_setup, online_durchfuehrung.'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='icon_alt',
            field=models.JSONField(blank=True, default=dict, help_text='Alt-Text für das LS-Icon, zweisprachig {"de": …, "en": …} (Barrierefreiheit: Screenreader, KI/MCP, Crawler).'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='materials',
            field=models.JSONField(blank=True, default=dict, help_text='Materialien und Raumhinweise, zweisprachig {"de": …, "en": …}.'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.JSONField(default=dict, help_text='Zweisprachiger Anzeigename als Objekt {"de": …, "en": …}, z. B. 1-2-4-All.'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='objective',
            field=models.JSONField(blank=True, default=dict, help_text='Kanonisches Ziel (LS Selection Matchmaker) zweisprachig {"de": …, "en": …}: das eine Ziel, das die Struktur erfüllt – Matching-Schlüssel. Quelle: data/ls_objectives.json.'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='scrum_use',
            field=models.JSONField(blank=True, default=dict, help_text='Einsatz im Scrum-Kontext (Retro, Planning, …), zweisprachig {"de": …, "en": …}.'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='short_desc',
            field=models.JSONField(default=dict, help_text='Zweisprachige Kurzbeschreibung {"de": …, "en": …} (je 1–3 Sätze).'),
        ),
    ]
