# Generated by Django 5.1.15 on 2026-06-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_structure_attribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='icon',
            field=models.CharField(blank=True, default='', help_text="Dateiname des offiziellen LS-Icons (in 'LS ICONS SVG/'), semantisch je Struktur zugeordnet. WICHTIG: Die Dateinummer entspricht NICHT der structure_id — die eindeutige Zuordnung steht in data/icon_map.json und wird hier importiert.", max_length=80),
        ),
    ]
